### ISSUE TITLE
Schematic & html styling

### ISSUE THREAD

**Issue by schooling** [stojanmar/ESP32-Si5351-FM-AM-TX-web-server#1]
Hi, Do you have a schematic for the wiring ?
There is a problem with the styling of the html. The html body will not show in Chrome or Edge. It will function when i remove the styling code.

**Comment by stojanmar** [comment]
The html part of the code works including styling. I just tried it once again this way. Copy that part of code and paste it to this simple tool:
[https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic](url)
Didnt make schematic yet, but I put some connection instructions to readme file.

**Comment by schooling** [comment]
The % character (font-size: 150% >>> font-size: 1.5)must be removed from line 115 in ..ulp5.ino, then the code can be read from the flash memory. The % was causing a break preventing the html progrem to be fully read.

i am still trying to figure out how to get the am signal - which pin ? i want to am modulate a 50kh squarewave single frequency with 3.1mhz carrier.

**Comment by stojanmar** [comment]
Thanks for comment back, but then I dont understand, why this works with me as it is. Will look at this at some convenient time. The AM out is on pin 26. This is anyway prescribed in readme file from beginning.  I am suspecting your signal with 50khz will not pass thrue, because my sampling is not sufitiently high.

**Comment by stojanmar** [comment]
Pin  26 is  analog value for AM power regulation.. Pin 25 is output with analog value with audio signal.

**Comment by stojanmar** [comment]
This discussion will be respected, while issuing a new version.
